server:
   port: 8100
spring:
   application:
      name: purchase-service
   datasource:
      url: jdbc:mysql://rm-bp1i9glrf4kptu1ppvo.mysql.rds.aliyuncs.com:3306/aipsi_cws?useSSL=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10