server:
   port: 8300
   forward-headers-strategy: framework
spring:
   rabbitmq:
      host: 129.204.75.127
      port: 5672
      username: admin
      password: '{cipher}589803053f2b951bd45b83b28b9a83e5a8c0e1a5900e333bf10171fc29546c8a'
   cloud:
      bus:
         enabled: true
         refresh:
            enabled: true
   datasource:
# 数据源
      url: jdbc:mysql://rm-bp1i9glrf4kptu1ppvo.mysql.rds.aliyuncs.com:3306/aipsi_cws?useSSL=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
      username: dbadmin
      password: '{cipher}eaa78751fc84ad9b1fd1795ce04c5595ba02bd880772100f9416a8d8e870c988'
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
# 连接池
      hikari:
         connection-timeout: 20000
         idle-timeout: 20000
         maximum-pool-size: 20
         minimum-idle: 5
         max-lifetime: 30000
         auto-commit: true
         pool-name: AipsiCwsHikari
management:
   security:
      enabled: false
   endpoints:
      web:
         exposure:
            include: '*'
feign:
   client:
      config:
         default:
            connectTimeout: 5000 #连接超时
            readTimeout: 5000 #读取超时
            loggerLevel: basic #日志等级
mybatis:
   mapper-locations: mapper/*Mapper.xml
# 实体类
   type-aliases-package: com.aipsi.cws.purchase.domain.*