server:
  port: 8200
  forward-headers-strategy: framework
spring:
  rabbitmq:
    host: 10.0.0.13
    port: 5672
    username: admin
    password: '{cipher}589803053f2b951bd45b83b28b9a83e5a8c0e1a5900e333bf10171fc29546c8a'
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
  datasource:
    url: jdbc:mysql://10.0.0.8:3306/aipsi_cws?useSSL=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: '{cipher}66e1b14991262af0cceb2a9597e10ef7464b0249e447d5f87fee80e2d45eeead'
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      idle-timeout: 20000
      maximum-pool-size: 20
      minimum-idle: 5
      max-lifetime: 30000
      auto-commit: true
      pool-name: AipsiCwsHikari
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
mybatis-plus:
  mapper-locations: mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-not-delete-value: 0
      logic-delete-value: 1