server:
   port: 8500
spring:
   rabbitmq:
      host: 129.204.75.127
      port: 5672
      username: admin
      password: '{cipher}589803053f2b951bd45b83b28b9a83e5a8c0e1a5900e333bf10171fc29546c8a'
   cloud:
      bus:
         enabled: true
         refresh:
            enabled: true
   datasource:
# 数据源
      url: jdbc:mysql://localhost:3306/AIPSI_CWS?useSSL=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
      username: root
      password: '{cipher}0bb57210c4597377f91c5149c1d286cdcd98bca1b8e8dc2d7a5ea42dc3c48fe0'
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
# 连接池
      hikari:
         connection-timeout: 20000
         idle-timeout: 20000
         maximum-pool-size: 20
         minimum-idle: 5
         max-lifetime: 30000
         auto-commit: true
         pool-name: AipsiCwsHikari
management:
   security:
      enabled: false
   endpoints:
      web:
         exposure:
            include: '*'
feign:
   client:
      config:
         default:
            connectTimeout: 5000 #连接超时
            readTimeout: 5000 #读取超时
            loggerLevel: basic #日志等级
mybatis:
   configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl