server:
   port: 8500
spring:
   application:
      name: customer-service
   datasource:
      url: jdbc:mysql://rm-bp1i9glrf4kptu1ppvo.mysql.rds.aliyuncs.com:3306/aipsi_cws?useSSL=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
      username: dbadmin
      password: '{cipher}eaa78751fc84ad9b1fd1795ce04c5595ba02bd880772100f9416a8d8e870c988'