server:
   port: 8500
spring:
   application:
      name: customer-service
   datasource:
      url: jdbc:mysql://localhost:3306/aipsi_cws?useSSL=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
      username: root
      password: null